name: AI Job Scorer

on:
  workflow_dispatch:  # Allow manual triggering
  repository_dispatch:
    types: [start-ai-scorer]

jobs:
  score-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install OpenAI for AI scoring
        pip install openai
        
    - name: Check environment setup
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Checking environment variables..."
        if [ -z "$SUPABASE_URL" ]; then
          echo "Warning: SUPABASE_URL is not set"
        else
          echo "SUPABASE_URL is configured"
        fi
        if [ -z "$SUPABASE_ANON_KEY" ]; then
          echo "Warning: SUPABASE_ANON_KEY is not set"
        else
          echo "SUPABASE_ANON_KEY is configured"
        fi
        if [ -z "$OPENAI_API_KEY" ]; then
          echo "Warning: OPENAI_API_KEY is not set (required for AI scoring)"
        else
          echo "OPENAI_API_KEY is configured"
        fi
        
    - name: Run AI job scorer
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Starting AI job scoring..."
        python job_scorer.py
        echo "AI job scoring completed successfully"
        
    - name: Upload artifacts (if any)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: scorer-results
        path: |
          *.json
          *.csv
        retention-days: 7
        
    - name: Send notification on success
      if: success()
      run: |
        echo "✅ AI job scoring completed successfully!"
        echo "📊 Jobs scored for CFO services"
        
    - name: Send notification on failure
      if: failure()
      run: |
        echo "❌ AI job scoring failed!"
        echo "Please check the logs for details" 