name: Daily Job Processing Orchestrator

on:
  schedule:
    # Run daily at 5:00 AM Danish time (CET/CEST)
    # This is 3:00 AM UTC in winter (CET) and 4:00 AM UTC in summer (CEST)
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  trigger-job-scraper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger job scraper
      run: |
        echo "Starting daily job processing chain..."
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"start-job-scraper"}'
        echo "Job scraper workflow triggered successfully"
        
    - name: Send notification
      run: |
        echo "🚀 Daily job processing chain initiated!"
        echo "📋 Workflow order: Scraper → Cleanup → AI Scorer" 