name: Job Validator

on:
  workflow_dispatch:  # Allow manual triggering
  repository_dispatch:
    types: [start-job-validator]

jobs:
  validate-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check environment setup
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        echo "Checking environment variables..."
        if [ -z "$SUPABASE_URL" ]; then
          echo "Warning: SUPABASE_URL is not set"
        else
          echo "SUPABASE_URL is configured"
        fi
        if [ -z "$SUPABASE_ANON_KEY" ]; then
          echo "Warning: SUPABASE_ANON_KEY is not set"
        else
          echo "SUPABASE_ANON_KEY is configured"
        fi
        
    - name: Run job validator (oldest jobs first)
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        echo "Starting GitHub Actions V2 job validation with fallback strategies..."
        python job_validator_github_actions_v2.py
        echo "Job validation completed successfully"
        
    - name: Check validator results
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        echo "Checking validator results..."
        python -c "
        from job_validator_github_actions_v2 import GitHubActionsJobValidatorV2
        validator = GitHubActionsJobValidatorV2()
        stats = validator.get_deletion_stats()
        print(f'Validator Results: {stats}')
        "
        
    - name: Trigger job scraper
      if: success()
      run: |
        echo "Triggering job scraper workflow..."
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"start-job-scraper"}'
        
    - name: Send notification on success
      if: success()
      run: |
        echo "✅ Job validation completed successfully!"
        echo "📊 Expired jobs cleaned up"
        
    - name: Send notification on failure
      if: failure()
      run: |
        echo "❌ Job validation failed!"
        echo "Please check the logs for details" 