name: Job Scraper

on:
  workflow_dispatch:  # Allow manual triggering
  repository_dispatch:
    types: [start-job-scraper]

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Playwright
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install chromium
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Check environment setup
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        echo "Checking environment variables..."
        if [ -z "$SUPABASE_URL" ]; then
          echo "Warning: SUPABASE_URL is not set"
        else
          echo "SUPABASE_URL is configured"
        fi
        if [ -z "$SUPABASE_ANON_KEY" ]; then
          echo "Warning: SUPABASE_ANON_KEY is not set"
        else
          echo "SUPABASE_ANON_KEY is configured"
        fi
        
    - name: Run scraper and cleanup
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        echo "Starting combined job scraper and cleanup..."
        python job_scraper_and_cleanup.py
        echo "Combined scraper and cleanup completed successfully"
        
    - name: Trigger AI job scorer
      if: success()
      run: |
        echo "Triggering AI job scorer workflow..."
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"start-ai-scorer"}'
        
    - name: Send notification on success
      if: success()
      run: |
        echo "✅ Combined scraper and cleanup completed successfully!"
        echo "📊 New jobs scraped and old jobs cleaned up"
        
    - name: Send notification on failure
      if: failure()
      run: |
        echo "❌ Job scraper failed!"
        echo "Please check the logs for details" 